---
title: "letterEditor_revision"
format: pdf
editor: visual
---

Dear Dr. Charles Canham,

I want to express my gratitude for taking the time to review our manuscript. Your insightful thoughts on our findings were very helpful.

In this revised version, we have addressed all the comments from the reviewers and we believe that the changes we made have significantly improved the manuscript.

Once again, I want to thank you for the time and effort you dedicated to reviewing our work. We look forward to hearing from you again.

Best regards,

Olalla Díaz-Yáñez on behalf of all the co-authors

## 

## Reviewer 1

Dear Reviewer 1,

Thank you for taking the time to review our manuscript. We appreciate your thoughtful comments and have carefully considered each of them. We have made changes to the manuscript based on your feedback and believe that these changes have improved the overall quality of the work.

Please find below our responses to each of your comments and the concrete actions we have taken in response.

Thank you again for your valuable feedback.
